# =========================
# DATABASE CONNECTION
# =========================

spring.datasource.url=jdbc:mysql://localhost:3306/fintrack
# tells Spring Boot where MySQL is

spring.datasource.username=root
# default MySQL username (change if yours is different)

spring.datasource.password=1234
# empty if using XAMPP default

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# MySQL driver

# =========================
# JPA / HIBERNATE SETTINGS
# =========================

spring.jpa.hibernate.ddl-auto=update
# auto creates tables from entities

spring.jpa.show-sql=true
# shows SQL in console (VERY useful for learning)

spring.jpa.properties.hibernate.format_sql=true
# makes SQL readable